# 1

In [ ]:
import numpy as np

sample_array = np.array([1, 2, 3, 4, 5])

mean_value = np.mean(sample_array)

variance_value = np.var(sample_array)

print("Mean of the sample array:", mean_value)
print("Variance of the sample array:", variance_value)


Mean of the sample array: 3.0
Variance of the sample array: 2.0


->  The mean gives an indication of the average value in the sample.
->  The variance quantifies how much the values in the sample deviate from the mean.

# 2

In [ ]:
import numpy as np

vector1 = np.array([2, 4, 6, 8, 10])
vector2 = np.array([1, 3, 5, 7, 9])

if vector1.shape[0] != vector2.shape[0]:
    raise ValueError("Vectors must be of the same length")

mean_vector1 = np.mean(vector1)
mean_vector2 = np.mean(vector2)

covariance = np.mean((vector1 - mean_vector1) * (vector2 - mean_vector2))

print("Covariance between the two vectors:", covariance)


Covariance between the two vectors: 8.0


->  Covariance quantifies the degree to which two variables change together. If the covariance is positive, it indicates that as one variable increases, the other tends to also increase. Conversely, if the covariance is negative, it means that as one variable increases, the other tends to decrease.

# 3

In [ ]:
import numpy as np

vector1 = np.array([2, 4, 6, 8, 10])
vector2 = np.array([1, 3, 5, 7, 9])

if vector1.shape[0] != vector2.shape[0]:
    raise ValueError("Vectors must be of the same length")

mean_vector1 = np.mean(vector1)
mean_vector2 = np.mean(vector2)

covariance = np.mean((vector1 - mean_vector1) * (vector2 - mean_vector2))

std_dev_vector1 = np.std(vector1)
std_dev_vector2 = np.std(vector2)

correlation = covariance / (std_dev_vector1 * std_dev_vector2)

print("Correlation between the two vectors:", correlation)


Correlation between the two vectors: 0.9999999999999998


->  Correlation quantifies the strength and direction of a linear relationship between two variables. It provides a normalized measure of how one variable moves in relation to another.



# 4

In [ ]:
import numpy as np

data_matrix = np.array([
    [2, 4, 6, 8],
    [1, 3, 5, 7],
    [5, 6, 2, 1]
])

covariance_matrix = np.cov(data_matrix, bias=False, rowvar=True)

correlation_matrix = np.corrcoef(data_matrix, rowvar=True)

print("Covariance Matrix:\n", covariance_matrix)
print("\nCorrelation Matrix:\n", correlation_matrix)


Covariance Matrix:
 [[ 6.66666667  6.66666667 -5.33333333]
 [ 6.66666667  6.66666667 -5.33333333]
 [-5.33333333 -5.33333333  5.66666667]]

Correlation Matrix:
 [[ 1.          1.         -0.86772183]
 [ 1.          1.         -0.86772183]
 [-0.86772183 -0.86772183  1.        ]]


->  Covariance Matrix: Provides insights into how features co-vary with each other.
It is useful to understand the direction and strength of the linear relationship between features but does not account for the scale of the features.

->  Correlation Matrix: Offers a normalized view of the relationships between features, making it easier to interpret the strength and direction of linear relationships without the influence of feature scales. This matrix is especially useful for identifying patterns and relationships between features in a standardized way.